version: '3.8'

services:
  user:
    build: .
    ports:
      - "5001:5001"  # проброс порта для сервера
    environment:
      PORT: 5001
      DATABASE_URL: "postgresql://postgres:postgres@host.docker.internal:5432/user"
    depends_on:
      - db
    networks:
      - user-network

  db:
    image: postgres:15-alpine
    container_name: user_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user
    ports:
      - "5432:5432"  # проброс порта базы данных
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-network

volumes:
  postgres_data:

networks:
  user-network:
    driver: bridge